// achievemnetItems.jsx

const items = [
    {id: 1, name: "Welcome to Nagasugai"},
    {id: 2, name: "Useful Features"},
    {id: 3, name: "Back into the Fray"},
    {id: 4, name: "No Prison Can Hold Me"},
    {id: 5, name: "Substory Baby"},
    {id: 6, name: "Reunited"},
    {id: 7, name: "The Chosen One"},
    {id: 8, name: "Japan Dome Awaits"},
    {id: 9, name: "You're the Princess"},
    {id: 10, name: "Out of the Park"},
    {id: 11, name: "Thank You!"},
    {id: 12, name: "Watch for Cars"},
    {id: 13, name: "Good Communicator"},
    {id: 14, name: "Veteran Driver"},
    {id: 15, name: "Devil Killers Defeated"},
    {id: 16, name: "Substory Prince"},
    {id: 17, name: "Singled Out"},
    {id: 18, name: "Yama-oroshi Defeated"},
    {id: 19, name: "Kitted Out"},
    {id: 20, name: "Tackler"},
    {id: 21, name: "Up-and-Coming Comedian"},
    {id: 22, name: "No Easy Way Out"},
    {id: 23, name: "Substory King"},
    {id: 24, name: "Full-fledged Hunter"},
    {id: 25, name: "Trendy Idol"},
    {id: 26, name: "Dragon Fury"},
    {id: 27, name: "End of the Line"},
    {id: 28, name: "Big Hitter"},
    {id: 29, name: "Fish for Dinner"},
    {id: 30, name: "Eyes on the Ground"},
    {id: 31, name: "A Bond Between Dancers"},
    {id: 32, name: "Life is About Learning"},
    {id: 33, name: "Major Revelation"},
    {id: 34, name: "Thrilling First Date"},
    {id: 35, name: "King of Cochin"},
    {id: 36, name: "Sightseeing Dragon"},
    {id: 37, name: "Reaching the Limit"},
    {id: 38, name: "Novice Snowball Fighter"},
    {id: 39, name: "Substory God"},
    {id: 40, name: "Old-school Gamer"},
    {id: 41, name: "Benevolent Dragon"},
    {id: 42, name: "Dream Ride"},
    {id: 43, name: "A Hearty Bowl"},
    {id: 44, name: "Puck Deflector"},
    {id: 45, name: "Top Ten"},
    {id: 46, name: "Puppet Master"},
    {id: 47, name: "Launch Striker"},
    {id: 48, name: "Ultimate Heir"},
    {id: 49, name: "Gourmet Dragon"},
    {id: 50, name: "A Toast Together"},
    {id: 51, name: "Mr. Climax"},
    {id: 52, name: "Local Framer"},
    {id: 53, name: "Life is Entertainment"},
    {id: 54, name: "Heir to the Legend"},
    {id: 55, name: "Hall of Famer"},
    {id: 56, name: "The Dream, Fullfilled"},
];

export default items;